services:
  gateway:
    build:
      context: .
      args:
        VERSION: ${VERSION}
    ports:
      - "8888:8888"
    env_file: .env
    command: ["/ika", "-config", "/ika.yaml"]
  httpbun:
    image: sharat87/httpbun
    expose: ["80"]

