services:
  gateway:
    build:
      context: .
      args:
        - BUILD_TAGS=${BUILD_TAGS}
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:6060:6060"
    command: ["/ika", "-config", "/config.yaml"]
    volumes:
      - ./tests/ika.yaml:/config.yaml
    env_file: example/.env

  example:
    build:
      context: .
      dockerfile: ./example/Dockerfile
      args:
        VERSION: ${VERSION}
    ports:
      - "127.0.0.1:1111:8888"
    env_file: example/.env
    command: ["/ika", "-config", "/ika.yaml"]
    volumes:
      - ./example/ika.yaml:/ika.yaml

  httpbun-local:
    image: sharat87/httpbun:dc21d845d1ec08a34559d1d075d7345b2941244d
    expose: ["80"]
    ports:
      - "127.0.0.1:8080:80"
