services:
  gateway:
    build: .
    ports:
      - "8888:8888"
      - "6060:6060"
    command: ["/ika", "-config", "/config.yaml"]
    volumes:
      - ./tests/ika.yaml:/config.yaml
    env_file: example/.env
  # krakend:
  #   image: devopsfaith/krakend
  #   command: ["run", "-c", "/config.json"]
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./tests/krakend.json:/config.json

  example:
    build:
      context: .
      dockerfile: ./example/Dockerfile
      args:
        VERSION: ${VERSION}
    ports:
      - "1111:8888"
    env_file: example/.env
    command: ["/ika", "-config", "/ika.yaml"]
    volumes:
      - ./example/ika.yaml:/ika.yaml

  httpbun-local:
    image: sharat87/httpbun
    expose: ["80"]
