name: Deployer

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./example
          file: ./example/Dockerfile
          push: true
          tags: ghcr.io/alx99/ika-example:latest
          build-args: |
            VERSION=${{ github.sha }}
  deploy-example:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Deploy
        run: curl "${{ secrets.DEPLOY_WEBHOOK }}"
