name: Test runner

on:
  push:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - uses: cue-lang/setup-cue@v1.0.1
      - name: Run E2E tests
        run: touch ./example/.env && make cfg-docker e2e-compose
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Image ika
        run: make image
      - name: Run ika with the example project
        run: touch ./example/.env && make upd
      - name: Check that the Cache-Control headers are set
        run: |
          curl localhost:1111/example/get -sD headers.txt
          grep "Expires: Thu, 01 Jan 1970 00:00:00 GMT" headers.txt
          grep "Pragma: no-cache" headers.txt
          grep "Cache-Control: no-cache, no-store, no-transform, must-revalidate, private, max-age=0" headers.txt
